version: '2'
services:
    amas-app:
        image: amas
        environment:
            - SPRING_PROFILES_ACTIVE=dev,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://amas-mysql:3306/amas?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=amas-elasticsearch:9300
        ports:
            - 8080:8080
    amas-mysql:
        extends:
            file: mysql.yml
            service: amas-mysql
    amas-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: amas-elasticsearch
